[workspace]
members = [
    "ark-cli",
    "data-error",
    "data-json",
    "data-link",
    "data-pdf",
    "data-resource",
    "fs-atomic-versions",
    "fs-cache",
    "fs-atomic-light",
    "fs-metadata",
    "fs-properties",
    "fs-index",
    "fs-storage",
    "dev-hash",
]

default-members = [
    "ark-cli",
    "data-error",
    "data-json",
    "data-link",
    "data-pdf",
    "data-resource",
    "fs-atomic-versions",
    "fs-cache",
    "fs-atomic-light",
    "fs-metadata",
    "fs-properties",
    "fs-index",
    "fs-storage",
    "dev-hash",
]

resolver = "2"
