verbose = "Verbose"
tab_spaces = 4

max_width = 80
chain_width = 50
single_line_if_else_max_width = 30

force_explicit_abi = true

report_todo = "Always"
report_fixme = "Always"

reorder_imports = true

wrap_comments = true

newline_style = "Unix"
