[package]
name = "receiver"
version = "1.1.0"
edition = "2024"

[dependencies]
entities = { path = "../../entities" }
common = { path = "../common" }

uuid = "1.16.0"
tokio = "1.44.2"
serde = "1.0.219"
anyhow = "1.0.98"
iroh-base = "0.34.1"
serde_json = "1.0.140"
iroh = { version = "0.34.1", default-features = false }
